title:  Ugochukwu Fabian Agbo
logo: Data.jpeg
description: "I am a data analyst with extensive experience in using Advanced Excel for report automation and Power BI for generating business insights."
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
