title:  Ugochukwu Fabian Agbo
logo: Data .jpeg
description: "I’m a data analyst skilled in automating reports with Advanced Excel, querying databases using SQL, and turning data into meaningful insights using Power BI."
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
